### PR TITLE
Handle the case when nonce is a base64 string for signMessage

### PR DESCRIPTION
**Pull request by kujtimprenkuSQA**
## Issues

Original issue: 

Currently the `nonce` is being passed as a string of [ASCII characters](https://www.asciitable.com/) characters  from `wallet-selector` in case the `nonce` Buffer contains any value greater than `128` it adds these symbols to the URL which results in strange behavior such as errors either like: 
_Array length 60 does not match schema length 32 at value.nonce_

OR

image

## Changes description

This PR adds the possibility to handle the case when the nonce is passed to the URL as a `base64` string which is more URL-safe but still keeps the old functionality to avoid breaking changes for the current and older versions of the `wallet-selector`

Changes made to wallet-selector to fix the issue: https://github.com/near/wallet-selector/pull/1067

### CODE REVIEW

**Comment by edwardchew97** [comment]
Thanks for submitting the PR, appreciate the work!
Looks clean and straight forward to me. Is there any testnet app where we can test out the this update?

**Comment by kujtimprenkuSQA** [comment]
> Thanks for submitting the PR, appreciate the work! Looks clean and straight forward to me. Is there any testnet app where we can test out the this update?

Hi, I just manually deployed the changes of this PR: https://github.com/near/wallet-selector/pull/1067 in `gh-pages`: https://near.github.io/wallet-selector

The walletUrl for MNW is set to the preview URL: https://deploy-preview-194--imaginative-sunflower-a54795.netlify.app/

**Review by edwardchew97 — APPROVED** [review]
Looks good, appreciate the contribution!

**Comment by kujtimprenkuSQA** [comment]
> Looks good, appreciate the contribution!

@edwardchew97 thank you for merging it.

Is there any estimated time on when it can be live on `mainnet` and `testnet`?

**Pull request merged**
